name: Build docker-alpine-oraclejdk8 and Publish Docker

on:
  push:
    paths:
      - Dockerfile
    branches:
      - main
    tags:
      - v1.*
      - v2.*
      - v3.*
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Fetch tags
      run: git fetch --prune --unshallow

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: bigrocs/docker-alpine-oraclejdk8
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        snapshot: true